# Generated by Django 5.2.3 on 2026-09-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=10, verbose_name='Tanlangan til')),
                ('is_admin', models.BooleanField(default=True, verbose_name='Admin ruxsati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
            ],
            options={
                'verbose_name': 'Telegram Foydalanuvchi',
                'verbose_name_plural': 'Telegram Foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
    ]
