# Generated by Django 5.2.3 on 2026-09-07 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='django_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='CRM Foydalanuvchisi'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='Tizimga kirgan'),
        ),
    ]
