# Generated by Django 5.2.3 on 2026-09-07 16:52

import crm.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_created_at_customer_is_connected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('is_connected', models.BooleanField(default=False, verbose_name="Bog'lanildi")),
                ('is_lead', models.BooleanField(default=False, verbose_name='Potensial mijoz (Lead)')),
                ('original_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Dastlab yaratilgan sana')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="O'chirilgan sana")),
                ('expires_at', models.DateTimeField(default=crm.models.get_default_expiration, verbose_name='Saqlanish muddati tugashi')),
            ],
            options={
                'verbose_name': 'Korzinkadagi mijoz',
                'verbose_name_plural': "Korzinka (O'chirilganlar)",
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name="Bog'lanildi"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_lead',
            field=models.BooleanField(default=False, verbose_name='Potensial mijoz (Lead)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon raqami'),
        ),
    ]
