# Generated by Django 5.2.3 on 2026-09-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customertrash_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='customertrash',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
    ]
